services:
  K10r\ViteEncoreBundle\Service\ManifestParser:
    arguments:
      $manifestPath: '%kernel.project_dir%/public/%k10r_vite_encore.base%/manifest.json'

  K10r\ViteEncoreBundle\Service\TagRenderer:

  K10r\ViteEncoreBundle\Service\EntrypointRenderer:
    arguments:
      $basePath: '%k10r_vite_encore.base%'
      $serverUrl: '%k10r_vite_encore.server%'
      $isDevServerEnabled: '%k10r_vite_encore.is_dev_server_enabled%'
      $environment: '%kernel.environment%'
      $manifestParser: '@K10r\ViteEncoreBundle\Service\ManifestParser'
      $tagRenderer: '@K10r\ViteEncoreBundle\Service\TagRenderer'

  K10r\ViteEncoreBundle\Twig\ViteEncoreExtension:
    arguments:
      $entrypointRenderer: '@K10r\ViteEncoreBundle\Service\EntrypointRenderer'
    tags: [twig.extension]
